import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from 'next/link';
import "./globals.css";
import Navbar from './navBar';
// import Navbar from './home/navBar';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
              
      <body className={inter.className}>
      <div>
      <Navbar /> 
      <div className="text-black">
        {children} 
      </div>
    </div>
        </body>
    </html>
  );
}
